Module7 task2
htmlacademy-ecmascript/700999-big-trip-12 pull request #12
Opened 2020-09-10 22:01 UTC by Makemanback

2020-09-11 04:32 UTC, Shv-sergey70 requested changes
1. Сортировка должна исчезать, когда мы на экране статистики.
2. Рядом с название каждого типа в стате есть emoji - надо их добавить. И все типы должны быть в верхнем регистре (судя по скриншоту в задании)

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/utils/statistics.js
> +    }, 0);
Можно просто инкрементировать значение аккумулятора
```
uniqueTravelTypes.forEach((type) => {
    const repeation = points.filter((point) => point.type === type)
    .reduce((accumulator) => {
      return ++accumulator;
    }, 0);
    obj[type] = repeation;
  });
```

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/utils/statistics.js
> +};
Этот код можно здорово оптимизировать, сделав все расчеты за один обход массива, без привлечения сторонней функции `createUniqeTypes `:
```
export const getPointByTypePrice = (points) => {
  const obj = {};

  points.forEach(({type, price}) => {
    if (obj[type]) {
      obj[type] += price;
    } else {
      obj[type] = price;
    }
  });

  return obj;
};
```

Точно также, аналогичным образом нужно сделать для других функций

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/utils/statistics.js
> +};
А это зачем?

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/utils/statistics.js
> +export const getTime = (start, end) => Math.round((end - start) / Time.MILLISECONDS / Time.SECONDS / Time.MINUTES);
Эта функция используется только в этом модуле, ее не нужно экспортировать. Проверь другие функции тоже

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/view/statistics.js
> +    return createStatisticsTemplate(this._data, StatsType);
Функция принимает только 1 параметр

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/view/statistics.js
> +    const BAR_HEIGHT = 55;
Константу надо вынести за пределы функции в этом модуле

2020-09-11 04:32 UTC, Shv-sergey70 commented on src/view/statistics.js
> +  const typesPrices = getPointByTypePrice(points);
Эта функции не должна вызываться здесь. Все расчеты должны проходить вне этой функции. Сама функция должна принимать только готовые данные для отрисовки. Иначе твоя функция `renderMoneyChart ` делает сразу 2 действия - готовит данные и рендерит

2020-09-13 08:10 UTC, Shv-sergey70 requested changes

2020-09-13 08:10 UTC, Shv-sergey70 commented on src/view/statistics.js
> +const renderMoneyChart = (moneyCtx, points) => {
Название второго параметра не соответствует содержимому

2020-09-13 08:10 UTC, Shv-sergey70 commented on src/view/statistics.js
> +const renderTransportChart = (transportCtx, points) => {
То же со вторым параметром что и выше. И ниже то же

2020-09-13 08:10 UTC, Shv-sergey70 commented on src/view/statistics.js
> +const createStatisticsTemplate = ({MONEY, TRANSPORT, TIME_SPEND}) => {
Метод не работает правильно:
![image](https://user-images.githubusercontent.com/35741647/93013469-fd4f6e80-f5d2-11ea-9a67-f4c9305b39b9.png)

Обрати внимание что ты передаешь в параметр при вызове

2020-09-13 08:10 UTC, Shv-sergey70 commented on src/const.js
> +export const StatsType = {
Это не используется

2020-09-13 13:09 UTC, Makemanback commented on src/utils/statistics.js
> +  const travelTypes = points.filter((point) => point.type !== NonTravelPoint.SIGHTSEEING && point.type !== NonTravelPoint.CHECK_IN && point.type !== NonTravelPoint.RESTAURANT).map((point) => point.ty
Согласано тз: "Диаграмма «Transport» показывает статистику по транспортным средствам, которыми придётся воспользоваться в путешествии. Диаграмма отвечает на вопрос: «Сколько раз нам придётся воспользоваться самолётом, такси и так далее?»"

2020-09-14 04:03 UTC, Shv-sergey70 commented on src/const.js
> +  'Restaurant': `🍴 RESTAURANT`
Ключи также можешь взять из перечисления `Type`

2020-09-14 04:03 UTC, merged

2020-09-14 05:14 UTC, Makemanback commented on src/const.js
> +  'Restaurant': `🍴 RESTAURANT`
Тут непонятно как - нельзя же в ключе написать Type.TAXI