Module8 task1
htmlacademy-ecmascript/700999-big-trip-12 pull request #13
Opened 2020-09-12 19:47 UTC by Makemanback

Первую часть сделал, но довольно криво. Не получается в мейне прокинуть нормально поинты, поэтому сделал в условии нуля точек. Наверно потому что эта логика у меня прописана в мейне, а не презентере. Как изменить - не знаю.

2020-09-13 08:13 UTC, Shv-sergey70 requested changes

2020-09-13 08:13 UTC, Shv-sergey70 commented on MD5:24:ef:94:d4:f0:47:a9:ea:eb:b7:3c:e3:09:5a:ec:95 SHA256:KW74mv2cSH6JA9+8cLAEQN0qSaXTasb2nzoSU8tIey4
> +-----BEGIN OPENSSH PRIVATE KEY-----
Этого файла не должно быть в репозитории

2020-09-13 08:13 UTC, Shv-sergey70 commented on MD5:24:ef:94:d4:f0:47:a9:ea:eb:b7:3c:e3:09:5a:ec:95 SHA256:KW74mv2cSH6JA9+8cLAEQN0qSaXTasb2nzoSU8tIey4.pub
> +ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmX+P+SnN/abjLSzMk7cmT0CnyEAsBg6zWrrmmSnwrz8GqK4rDj6tWVZrXdYQpVhq/VkxZCwa4e28TRDKpmAGct2PlPnFfmrbggSrqrditLuhtT6U46JhQ38cp8U33AYLunPJ3sC+D/679/Zg1eU6T4AsFR5WoQmF
Этого файла не должно быть в репозитории

2020-09-13 08:13 UTC, Shv-sergey70 commented on src/presenter/trip.js
> +        this._pointsModel.get().length > 0 ? this._renderTripInfo() : this._renderEmptyTripInfo();
Сделай для этой логики `this._pointsModel.get().length > 0` отдельный метод в модели

2020-09-13 08:13 UTC, Shv-sergey70 commented on src/api.js
> +export default class Api {
Нигде не используется?

2020-09-13 13:39 UTC, Makemanback commented on src/api.js
> +export default class Api {
Используется

2020-09-14 04:44 UTC, Shv-sergey70 requested changes
Надо поправить ошибку обновления данных. На скриншоте способ понять, что пошло не так:
![image](https://user-images.githubusercontent.com/35741647/93044707-9e93fe80-f67f-11ea-9a15-428b3d7b6c9c.png)

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/mock/trip-day.js
> +export const DESTINATIONS = [
Все моки нужно удалить, так как теперь работа с сервером

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/model/points.js
> +  setOffers(offers) {
Попробуй сделать отдельные модели для `offers` и `destinations`

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/model/points.js
> +    return this._points.slice().sort((a, b) => a.schedule.start - b.schedule.start).map((item) => item.destination.name);
Деструктурируй в последнем `map`

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/view/trip-edit.js
> +    const destinationPoint = this._destinations.filter((destination) => destination.name === city);
Деструктурируй

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/view/trip-edit.js
> +    const destinationPoint = this._destinations.filter((destination) => destination.name === city);
Лучше подойдет метод `find`, а не `filter`, тогда вернется сразу нужный объект, а не массив с одним объектом

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/view/trip-edit.js
> +      name: evt.target.value,
`evt.target.value` можно не писать, так как это есть в переменной `city`

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/view/trip-edit.js
> +    const validationValue = this._destinations.map((item) => item.name).some((item) => item === cityInput.value) ? `` : `Please choose city from the list`;
Дейструктурируй

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/presenter/trip.js
> +    if (points.length === 0) {
Ты же создавал метод в модели для этого условия, используй его

2020-09-14 04:44 UTC, Shv-sergey70 commented on src/presenter/trip.js
> +    this._getStartDates = this._pointsModel.getStartDates();
А зачем даты сохранять как свойство конструктора? Вроде только в данном методе используется. Тогда будет достаточно и локальной переменной

2020-09-16 05:07 UTC, Shv-sergey70 commented on src/const.js
> +  'restaurant': `🍴 RESTAURANT`
Стоит сделать так для всех ключей:
```
export const ActionIcon = {
  [Type.TAXI]: `🚕 TAXI`,
  [Type.BUS]: `🚌 BUS`,
  'train': `🚂 TRAIN`,
  'ship': `🚢 SHIP`,
  'transport': `🚙 TRANSPORT`,
  'drive': `🚗 DRIVE`,
  'flight': `✈️ FLIGHT`,
  'check-in': `🏨 CHECK-IN`,
  'sightseeing': `🏛 SIGHTSEEING`,
  'restaurant': `🍴 RESTAURANT`
};
```

2020-09-16 05:07 UTC, merged